# Generated by Selenium IDE
import time
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By


class Test():
  def setup_method(self, method):
    chrome_fuyong = Options()
    # 和浏览器打开的测试端口进行通信
    # 浏览器复用，例子：命令行输入chrome --remote-debugging-port=8888(端口号随便输)  开启调试模式
    chrome_fuyong.debugger_address = "127.0.0.1:8888"
    self.driver = webdriver.Chrome(options=chrome_fuyong)

  def test_baidu(self):
    self.driver.get("https://www.baidu.com/")
    self.driver.find_element(By.ID, "kw").send_keys("霍格沃兹测试学院")
    self.driver.find_element(By.ID, "su").click()
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "霍格沃兹测试学院-软件自动化测试开发培训_接口性能测试").click()
